export interface StaffResponseModel {
    address: string,
    cardId: string,
    birthday: number,
    email: string,
    gender: boolean,
    image: string,
    name: string,
    pass: string,
    phone: string,
    role: boolean,
    deleted: boolean,
    staffId: number,
    pages: number,
}